name = "vfi"
uuid = "2b46deca-1448-4368-992d-484c512fc6b3"
authors = ["avinno <avinnofaruk@gmail.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Interpolations = "0.15.1"
LinearAlgebra = "1.11.0"
Plots = "1.40.8"
Roots = "2.2.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
